spring:
  application:
    name: batch-postgres-practice

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: jhkang
    password: 0000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always

